- name: Remove system default server
  file:
    path=/etc/nginx/conf.d/default.conf
    state=absent

- name: Write config files
  template:
    src=nginx.conf.j2
    dest=/etc/nginx/nginx.conf
    mode=0644
  notify: reload nginx
